// <auto-generated />
using System;
using FIT_Online_shop.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FIT_Online_shop.Migrations
{
    [DbContext(typeof(MojDbContext))]
    [Migration("20190528071522_Dostava")]
    partial class Dostava
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FIT_Online_shop.EntityModels.AutentifikacijaToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IpAdresa");

                    b.Property<int>("KorisnickiNalogId");

                    b.Property<string>("Vrijednost");

                    b.Property<DateTime>("VrijemeEvidentiranja");

                    b.HasKey("Id");

                    b.HasIndex("KorisnickiNalogId");

                    b.ToTable("AutentifikacijaToken");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.KorisnickiNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("KorisnickoIme");

                    b.Property<string>("Lozinka");

                    b.HasKey("Id");

                    b.ToTable("KorisnickiNalog");

                    b.HasDiscriminator<string>("Discriminator").HasValue("KorisnickiNalog");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Cijena");

                    b.Property<DateTime>("DatumNarudzbe");

                    b.Property<string>("DostavaAdresa");

                    b.Property<string>("DostavaIme");

                    b.Property<int>("DostavaOpstina");

                    b.Property<int?>("DostavaOpstinaIDId");

                    b.Property<string>("DostavaPostanskiBroj");

                    b.Property<string>("DostavaTelefon");

                    b.Property<string>("Napomena");

                    b.HasKey("Id");

                    b.HasIndex("DostavaOpstinaIDId");

                    b.ToTable("Narudzba");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.NarudzbaStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Kolicina");

                    b.Property<int>("NarudzbaID");

                    b.Property<int>("ProizvodID");

                    b.HasKey("Id");

                    b.HasIndex("NarudzbaID");

                    b.HasIndex("ProizvodID");

                    b.ToTable("NarudzbaStavka");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.Opstina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.ToTable("Opstina");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Cijena");

                    b.Property<string>("JedinicaMjere");

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.Kupac", b =>
                {
                    b.HasBaseType("FIT_Online_shop.EntityModels.KorisnickiNalog");

                    b.Property<string>("Ime");

                    b.Property<string>("Prezime");

                    b.HasDiscriminator().HasValue("Kupac");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.AutentifikacijaToken", b =>
                {
                    b.HasOne("FIT_Online_shop.EntityModels.KorisnickiNalog", "KorisnickiNalog")
                        .WithMany()
                        .HasForeignKey("KorisnickiNalogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.Narudzba", b =>
                {
                    b.HasOne("FIT_Online_shop.EntityModels.Opstina", "DostavaOpstinaID")
                        .WithMany()
                        .HasForeignKey("DostavaOpstinaIDId");
                });

            modelBuilder.Entity("FIT_Online_shop.EntityModels.NarudzbaStavka", b =>
                {
                    b.HasOne("FIT_Online_shop.EntityModels.Narudzba", "Narudzba")
                        .WithMany()
                        .HasForeignKey("NarudzbaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FIT_Online_shop.EntityModels.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
